server:
  port: XXX
logging:
  path: /XXX

spring:
  datasource:
    url: jdbc:XXX
    username: XXX
    password: XXX
    driver-class-name: com.mysql.cj.jdbc.Driver
  ftp:
    ip: XXX
    port: XXX
    username: XXX
    password: XXX
    path: /XXX